#!/bin/bash
THIS_SOURCE="$(dirname ${BASH_SOURCE[0]})"
echo Running scripts from: $THIS_SOURCE

. $THIS_SOURCE/../../control_scripts.sh

# ilo_power_off_these_hosts "$OVERCLOUD_HOSTS"
# # Toggle boot drives to stack, if necessary
# ilo_boot_set_onetimeboot_these_hosts ip "$ILO4_HOSTS"
# ilo_power_on_these_hosts "$ILO4_HOSTS"
# # Replace drives in Gen6 hosts manually

PROCEED=""
while [[ $PROCEED != "yes" ]]; do
  read -p "Ready?  Type 'yes' (in lowercase) to proceed:" PROCEED
done

ilo_power_off_these_hosts "$OVERCLOUD_HOSTS"
os_control_boot_to_target_installation admin "$OVERCLOUD_HOSTS"

ssh_control_run_as_user root "blkid" "$OVERCLOUD_HOSTS"

echo "We're done here!"
