#!/bin/bash
THIS_SOURCE="$(dirname ${BASH_SOURCE[0]})"
echo Running scripts from: $THIS_SOURCE

. $THIS_SOURCE/../../control_scripts.sh

ilo_power_off_these_hosts "$OVERCLOUD_HOSTS"
# Toggle boot drives to stack, if necessary
ilo_boot_set_onetimeboot_these_hosts ip "$ILO4_HOSTS"
ilo_power_on_these_hosts "$ILO4_HOSTS"
# Replace drives in Gen6 hosts manually


os_control_boot_to_target_installation default dmb
# ssh_control_run_as_user root "rm /root/undercloud_install*; tmux new-session -d -s undercloud 'DEFOPTS=true /home/cliff/CODE/feralcoder/train8/setup_undercloud.sh > undercloud_install_\$\$.log'; tmux split-window -t undercloud -h 'tail -f /root/undercloud_install_\$\$'" dmb

PROCEED=""
while [[ $PROCEED != "yes" ]]; do
  read -p "Ready?  Type 'yes' (in lowercase) to proceed:" PROCEED
done


echo "We're done here!"
