#!/bin/bash
THIS_SOURCE="$(dirname ${BASH_SOURCE[0]})"
echo Running scripts from: $THIS_SOURCE

. $THIS_SOURCE/../control_scripts.sh

for i in $ALL_HOSTS; do ssh_control_run_as_user root "echo $i > /root/abbrev_hostname" $i; done
ssh_control_sync_as_user_these_hosts root $THIS_SOURCE/fix_grub /tmp/fix_grub "$ALL_HOSTS"
ssh_control_sync_as_user_these_hosts root $THIS_SOURCE/no_crossboot /tmp/no_crossboot "$ALL_HOSTS"
ssh_control_run_as_user_these_hosts root "chmod 755 /tmp/no_crossboot /tmp/fix_grub; /tmp/no_crossboot; TIMEOUT=30 /tmp/fix_grub" "$ALL_HOSTS"
